services:

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
    environment:
      APP_MANAGEMENT_PORT: 8036
    volumes:
      - ./docker/config/prometheus:/etc/prometheus
      - ./docker/data/prometheus:/prometheus
    command: --web.enable-lifecycle --enable-feature=expand-external-labels --config.file=/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - 3000:3000
    depends_on:
      - prometheus
    volumes:
      - ./docker/config/grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./docker/config/grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yaml
      - ./docker/data/grafana:/var/lib/grafana
    links:
      - prometheus
