
server:
    port: 8100

management:
    server:
        port: 8101
    tracing:
        enabled: true
    metrics:
        tags:
            application: ${spring.application.name}
    observations:
        key-values:
            application: ${spring.application.name}
    endpoints:
        web:
            base-path: /
            exposure:
                include: health, env, info, metrics, prometheus, loggers, httptrace, beans, httpexchanges

spring:
    application:
        name: spring-internals
    threads:
        virtual:
            enabled: true

logging:
    pattern:
        level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
        #level: "%5p"
    level:
        jdk.internal.net.http: DEBUG
        org.apache.hc: DEBUG
        org.apiphany: DEBUG
        org.springframework.boot.context.logging: DEBUG

clients:
    compression:
        gzip: false
    custom:
        java-net-http:
            request:
                version: HTTP/1.1
        http-client-5:
            request:
                protocol-upgrade-enabled: false
                protocol-version: HTTP/2

apiphany-tests:
    base-url: http://localhost:8666

performance:
    enabled:
        - ApiPerformance
